#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

ENV_FILE="${ENV_FILE:-.scratch/dev-setup.env}"
mkdir -p "$(dirname "$ENV_FILE")"

upsert_local_properties() {
  local key="$1" value="$2" file="local.properties" tmp
  touch "$file"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$file" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$file"
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$file"
}

append_line_if_missing() {
  local file="$1" line="$2"
  touch "$file"
  if ! grep -Fqx "$line" "$file"; then
    printf '%s\n' "$line" >> "$file"
    printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$line" "$file"
  else
    note "already present in $file: $line"
  fi
}

resolve_bin() {
  local preferred="$1" fallback="$2"
  if [[ -x "$preferred" ]]; then
    printf '%s' "$preferred"
  elif command -v "$fallback" >/dev/null 2>&1; then
    command -v "$fallback"
  else
    printf ''
  fi
}

TOTAL_STAGES=9

banner "Light SDK CLI-only bootstrap"

stage "Install prerequisites"
say "We'll verify tooling and only open install links for missing tools."
step "Required: git, java (JDK 17), curl, unzip"
step "Optional: gh"

for cmd in git java curl unzip; do
  if command -v "$cmd" >/dev/null 2>&1; then
    say "Found: $cmd"
  else
    warn "Missing: $cmd"
    SKIPPED+=("Install missing prerequisite: $cmd")
  fi
done

if command -v gh >/dev/null 2>&1; then
  say "Found: gh"
else
  warn "Missing: gh (optional)"
  open_url "https://cli.github.com/"
  SKIPPED+=("Install GitHub CLI (optional)")
fi

pause "Press Enter to continue"

stage "Set SDK and JDK paths"
say "We'll store local paths in $ENV_FILE and local.properties."
ask ANDROID_SDK_ROOT "Paste ANDROID_SDK_ROOT (example: ~/Android/Sdk):"
ask JAVA_HOME "Paste JAVA_HOME (JDK 17 home path):"
ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT/#\~/$HOME}"
JAVA_HOME="${JAVA_HOME/#\~/$HOME}"
write_env ANDROID_SDK_ROOT "$ANDROID_SDK_ROOT"
write_env JAVA_HOME "$JAVA_HOME"
upsert_local_properties "sdk.dir" "$ANDROID_SDK_ROOT"
mkdir -p "$ANDROID_SDK_ROOT"

if [[ -n "${SHELL:-}" && "${SHELL##*/}" == "zsh" ]]; then
  PROFILE_FILE="$HOME/.zshrc"
elif [[ -n "${SHELL:-}" && "${SHELL##*/}" == "bash" ]]; then
  PROFILE_FILE="$HOME/.bashrc"
else
  PROFILE_FILE="$HOME/.profile"
fi

append_line_if_missing "$PROFILE_FILE" "export ANDROID_SDK_ROOT=\"$ANDROID_SDK_ROOT\""
append_line_if_missing "$PROFILE_FILE" "export JAVA_HOME=\"$JAVA_HOME\""
append_line_if_missing "$PROFILE_FILE" "export PATH=\"$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator:$JAVA_HOME/bin:\$PATH\""

export ANDROID_SDK_ROOT="$ANDROID_SDK_ROOT"
export JAVA_HOME="$JAVA_HOME"
export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator:$JAVA_HOME/bin:$PATH"

say "Updated current shell PATH for this wizard run."
note "Open a new shell (or run: source $PROFILE_FILE) after setup."

CMDLINE_TOOLS_BIN="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin"
SDKMANAGER="$(resolve_bin "$CMDLINE_TOOLS_BIN/sdkmanager" sdkmanager)"
AVDMANAGER="$(resolve_bin "$CMDLINE_TOOLS_BIN/avdmanager" avdmanager)"

stage "Install Android command-line tools"
if [[ -n "$SDKMANAGER" && -n "$AVDMANAGER" ]]; then
  say "cmdline-tools already installed."
  note "sdkmanager: $SDKMANAGER"
  note "avdmanager: $AVDMANAGER"
else
  warn "cmdline-tools not found; downloading release zip."
  open_url "https://developer.android.com/tools#tools-sdk"
  step "Copy the direct command-line tools ZIP URL for your OS."
  ask CMDLINE_TOOLS_URL "Paste command-line tools ZIP URL:"
  write_env CMDLINE_TOOLS_URL "$CMDLINE_TOOLS_URL"

  if [[ -z "$CMDLINE_TOOLS_URL" ]]; then
    warn "No URL provided; cannot install cmdline-tools."
    SKIPPED+=("Install Android cmdline-tools")
  else
    TMP_DIR=$(mktemp -d)
    ZIP_PATH="$TMP_DIR/cmdline-tools.zip"
    EXTRACT_DIR="$TMP_DIR/extract"
    mkdir -p "$EXTRACT_DIR"

    if curl -fL "$CMDLINE_TOOLS_URL" -o "$ZIP_PATH"; then
      unzip -q "$ZIP_PATH" -d "$EXTRACT_DIR"
      mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
      rm -rf "$ANDROID_SDK_ROOT/cmdline-tools/latest"
      if [[ -d "$EXTRACT_DIR/cmdline-tools" ]]; then
        mv "$EXTRACT_DIR/cmdline-tools" "$ANDROID_SDK_ROOT/cmdline-tools/latest"
      else
        mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
        mv "$EXTRACT_DIR"/* "$ANDROID_SDK_ROOT/cmdline-tools/latest/"
      fi
      say "Installed cmdline-tools to $ANDROID_SDK_ROOT/cmdline-tools/latest"
      SDKMANAGER="$(resolve_bin "$CMDLINE_TOOLS_BIN/sdkmanager" sdkmanager)"
      AVDMANAGER="$(resolve_bin "$CMDLINE_TOOLS_BIN/avdmanager" avdmanager)"
    else
      warn "Failed to download cmdline-tools from provided URL."
      SKIPPED+=("Install Android cmdline-tools")
    fi
    rm -rf "$TMP_DIR"
  fi
fi

stage "Install SDK packages with sdkmanager"
if [[ -z "$SDKMANAGER" ]]; then
  warn "sdkmanager unavailable."
  SKIPPED+=("Install SDK packages via sdkmanager")
else
  if [[ "$(uname -m)" == "arm64" || "$(uname -m)" == "aarch64" ]]; then
    DEFAULT_ABI="arm64-v8a"
  else
    DEFAULT_ABI="x86_64"
  fi

  ask ANDROID_ABI "ABI for API 34 image (default: $DEFAULT_ABI):"
  [[ -z "$ANDROID_ABI" ]] && ANDROID_ABI="$DEFAULT_ABI"

  ask ANDROID_TAG "System image tag (default: default):"
  [[ -z "$ANDROID_TAG" ]] && ANDROID_TAG="default"

  SYSTEM_IMAGE_PACKAGE="system-images;android-34;$ANDROID_TAG;$ANDROID_ABI"
  write_env ANDROID_ABI "$ANDROID_ABI"
  write_env ANDROID_TAG "$ANDROID_TAG"
  write_env ANDROID_SYSTEM_IMAGE "$SYSTEM_IMAGE_PACKAGE"

  say "Accepting SDK licenses..."
  yes | "$SDKMANAGER" --sdk_root="$ANDROID_SDK_ROOT" --licenses >/dev/null || true

  if "$SDKMANAGER" --sdk_root="$ANDROID_SDK_ROOT" \
      "platform-tools" \
      "emulator" \
      "platforms;android-34" \
      "$SYSTEM_IMAGE_PACKAGE"; then
    say "Installed platform-tools, emulator, android-34 platform, and system image."
  else
    warn "sdkmanager install failed."
    SKIPPED+=("Install SDK packages via sdkmanager")
  fi
fi

stage "Create AVD with avdmanager"
if [[ -z "$AVDMANAGER" ]]; then
  warn "avdmanager unavailable."
  SKIPPED+=("Create AVD with avdmanager")
else
  ask LIGHT_AVD_NAME "AVD name (default: light-phone-iii-api34):"
  [[ -z "$LIGHT_AVD_NAME" ]] && LIGHT_AVD_NAME="light-phone-iii-api34"
  write_env LIGHT_AVD_NAME "$LIGHT_AVD_NAME"

  if "$AVDMANAGER" list avd | grep -q "Name: $LIGHT_AVD_NAME"; then
    note "AVD already exists: $LIGHT_AVD_NAME"
  else
    if echo "no" | "$AVDMANAGER" create avd \
        --name "$LIGHT_AVD_NAME" \
        --package "$SYSTEM_IMAGE_PACKAGE" \
        --device "pixel_5"; then
      say "Created AVD: $LIGHT_AVD_NAME"
    else
      warn "Failed to create AVD."
      SKIPPED+=("Create AVD with avdmanager")
    fi
  fi
fi

stage "Boot and prepare emulator (system-app step 2)"
EMULATOR_BIN="$(resolve_bin "$ANDROID_SDK_ROOT/emulator/emulator" emulator)"
ADB_BIN="$(resolve_bin "$ANDROID_SDK_ROOT/platform-tools/adb" adb)"

if [[ -z "$LIGHT_AVD_NAME" ]]; then
  LIGHT_AVD_NAME="light-phone-iii-api34"
fi

if [[ -x "$HOME/.android/avd/$LIGHT_AVD_NAME.avd/config.ini" ]]; then
  AVD_CONFIG="$HOME/.android/avd/$LIGHT_AVD_NAME.avd/config.ini"
  sed -i.bak '/^hw.lcd.width=/d;/^hw.lcd.height=/d;/^hw.lcd.density=/d;/^skin.name=/d;/^skin.path=/d' "$AVD_CONFIG" || true
  printf '%s\n' "hw.lcd.width=1080" >> "$AVD_CONFIG"
  printf '%s\n' "hw.lcd.height=1240" >> "$AVD_CONFIG"
  printf '%s\n' "hw.lcd.density=320" >> "$AVD_CONFIG"
  printf '%s\n' "skin.name=1080x1240" >> "$AVD_CONFIG"
  printf '%s\n' "skin.path=_no_skin" >> "$AVD_CONFIG"
  say "Applied LP3-like display settings to $AVD_CONFIG"
else
  warn "AVD config not found; skipped display tuning."
fi

if [[ -n "$EMULATOR_BIN" && -n "$ADB_BIN" ]]; then
  if confirm "Launch emulator with -writable-system now?"; then
    "$EMULATOR_BIN" -avd "$LIGHT_AVD_NAME" -writable-system >/dev/null 2>&1 &
    sleep 5
    "$ADB_BIN" wait-for-device || true
    "$ADB_BIN" root || true
    if ! "$ADB_BIN" remount; then
      warn "adb remount failed. If verity is enabled, run: adb disable-verity && adb reboot"
      SKIPPED+=("If needed: adb disable-verity && adb reboot && adb root && adb remount")
    fi
    step "Sanity check test-keys: $ADB_BIN shell getprop ro.build.description"
  else
    SKIPPED+=("Boot emulator with -writable-system and run adb remount")
  fi
else
  warn "emulator/adb not found."
  SKIPPED+=("Boot and prepare emulator for system app install")
fi

stage "System-app setup steps 3-5"
if confirm "Run system-app install workflow now?"; then
  mkdir -p sdk/emulator/keys

  if [[ ! -f sdk/emulator/keys/platform.jks ]]; then
    step "Generating platform signing keystore at sdk/emulator/keys/platform.jks"
    curl -fL "https://raw.githubusercontent.com/wfairclough/android_aosp_keys/refs/heads/master/platform.x509.pem" -o /tmp/platform.x509.pem
    curl -fL "https://raw.githubusercontent.com/wfairclough/android_aosp_keys/refs/heads/master/platform.pk8" -o /tmp/platform.pk8
    openssl pkcs8 -inform DER -nocrypt -in /tmp/platform.pk8 -out /tmp/platform.pem
    openssl pkcs12 -export -in /tmp/platform.x509.pem -inkey /tmp/platform.pem -name platform -out /tmp/platform.p12 -passout pass:android
    keytool -importkeystore -srckeystore /tmp/platform.p12 -srcstoretype PKCS12 -srcstorepass android -destkeystore sdk/emulator/keys/platform.jks -deststoretype JKS -deststorepass android -noprompt
    rm -f /tmp/platform.pk8 /tmp/platform.x509.pem /tmp/platform.pem /tmp/platform.p12
    say "Generated platform.jks"
  else
    note "platform.jks already exists; skipping generation."
  fi

  if ./gradlew :sdk:emulator:assembleDebug --stacktrace; then
    say "Built emulator APK."
  else
    warn "Failed to build :sdk:emulator:assembleDebug"
    SKIPPED+=("Build sdk emulator APK")
  fi

  if [[ -n "$ADB_BIN" ]]; then
    "$ADB_BIN" shell mkdir -p /system/priv-app/LightOSEmulator || true
    "$ADB_BIN" push sdk/emulator/build/outputs/apk/debug/emulator-debug.apk /system/priv-app/LightOSEmulator/LightOSEmulator.apk || true
    "$ADB_BIN" reboot || true
    "$ADB_BIN" wait-for-device || true
    step "Verify install path: $ADB_BIN shell pm path com.thelightphone.sdk.emulator"
    step "Verify uid=1000: $ADB_BIN shell dumpsys package com.thelightphone.sdk.emulator | grep uid="
  else
    warn "adb unavailable; cannot push privileged app."
    SKIPPED+=("Install emulator APK as privileged system app")
  fi
else
  SKIPPED+=("Run system-app steps 3-5")
fi

stage "System-app steps 6-8 (post-setup options)"
if [[ -n "$ADB_BIN" ]]; then
  if confirm "Run step 6 quick reinstall command now?"; then
    ./gradlew :sdk:emulator:assembleDebug --stacktrace || true
    "$ADB_BIN" install -r sdk/emulator/build/outputs/apk/debug/emulator-debug.apk || true
  else
    note "Step 6 skipped."
  fi

  if confirm "Set LightOS emulator as launcher (step 7)?"; then
    "$ADB_BIN" shell cmd package set-home-activity com.thelightphone.sdk.emulator/.MainActivity || true
  else
    note "Step 7 skipped."
  fi

  if confirm "Disable animations (step 8)?"; then
    "$ADB_BIN" shell settings put global window_animation_scale 0 || true
    "$ADB_BIN" shell settings put global transition_animation_scale 0 || true
    "$ADB_BIN" shell settings put global animator_duration_scale 0 || true
  else
    note "Step 8 skipped."
  fi
else
  SKIPPED+=("Run system-app steps 6-8 (adb unavailable)")
fi

stage "Sanity checks"
if [[ -n "$ADB_BIN" ]]; then
  step "Check emulator app path"
  "$ADB_BIN" shell pm path com.thelightphone.sdk.emulator || true
  step "Check uid"
  "$ADB_BIN" shell dumpsys package com.thelightphone.sdk.emulator | grep "uid=" || true
  step "Check build description ends with test-keys"
  "$ADB_BIN" shell getprop ro.build.description || true
fi

if confirm "Run ./gradlew check now?"; then
  ./gradlew check --stacktrace || SKIPPED+=("Fix failing ./gradlew check")
else
  SKIPPED+=("Run ./gradlew check")
fi

if confirm "Run ./gradlew :light-page:assembleDebug now?"; then
  ./gradlew :light-page:assembleDebug --stacktrace || SKIPPED+=("Fix failing ./gradlew :light-page:assembleDebug")
else
  SKIPPED+=("Run ./gradlew :light-page:assembleDebug")
fi

if command -v gh >/dev/null 2>&1; then
  if gh auth status >/dev/null 2>&1; then
    say "gh is authenticated."
  else
    warn "gh installed but not authenticated."
    SKIPPED+=("Run gh auth login")
  fi
fi

finish
